[package]
name = "aalo"
version = "0.0.0"
edition = "2021"
categories = ["asynchronous", "gui", "game-development"]
description = "aka bevy-inspector-haalka, a port of bevy-inspector-egui"
exclude = ["assets/", ".github/", "crates/"]
keywords = ["ui", "reactive", "signals", "gamedev", "bevy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/databasedav/aalo"
documentation = "https://docs.rs/aalo"

[dependencies]
